mysql:
  auth:
    database: snippetbox
    rootPassword: root
    username: web
    password: pass
  initdbScriptsConfigMap: snippetbox-mysql-initdb

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
