apiVersion: v1
kind: Secret
metadata:
  name: snippetbox-tls-secret
  labels:
    {{- include "snippetbox.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{- if and .Values.tls.crt (ne .Values.tls.crt "") }}
    {{ .Values.tls.crt | b64enc }}
  {{- else }}
    {{ .Files.Get .Values.tls.crtFile | b64enc }}
  {{- end }}
  tls.key: {{- if and .Values.tls.key (ne .Values.tls.key "") }}
    {{ .Values.tls.key | b64enc }}
  {{- else }}
    {{ .Files.Get .Values.tls.keyFile | b64enc }}
  {{- end }}
