apiVersion: v1
kind: Secret
metadata:
  name: snippetbox-tls-secret
  labels:
    {{- include "snippetbox.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.tls.crtFile | b64enc }}
  tls.key: {{ .Files.Get .Values.tls.keyFile | b64enc }}
